name: Patrol Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  patrol-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Install Patrol CLI
        run: dart pub global activate patrol_cli

      - name: Run Patrol test
        run: |
          patrol test -t integration_test/login_test.dart \
            --verbose \
            --no-uninstall
